databases:
  - name: tattoo_app_db
    databaseName: tattoo_app_production
    user: tattoo_app
    plan: free

services:
  - type: web
    name: tattoo-app
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tattoo_app_db
          property: connectionString
      - key: POSTGRES_USER
        fromDatabase:
          name: tattoo_app_db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: tattoo_app_db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: tattoo_app_db
          property: host
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
